### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#1]
Add a link to print the map.

How we should do that? Deploy a print a server in the build or use an existing one ?

Update: 
 - don't print measure drawn
 - use http://api3.geo.admin.ch/print/
 - see the print component to see how it's done: https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js

**Comment by gjn** [comment]
I would propose to use the existing one from api3, if possible.

**Comment by cedricmoullet** [comment]
Use an existing one

Envoyé de mon iPhone

**Comment by oterral** [comment]
Sounds good to me. But if we want to do like hanspi said "deploy and forget" we should have a specific one no ?  but we have 3 years to think about this ;)

**Comment by oterral** [comment]
Available on prod
