### ISSUE TITLE
Search of coordinates

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#15]
We must add the possibility to type coordinates in the search box.

**Comment by p1d1d1** [comment]
There is an issue with the CSS, I guess.
The search div spans over the map: cannot pan.
Thanks

**Comment by kandre** [comment]
That's right, thank you for that information, it is solved via this commit https://github.com/geoadmin/web-emapis/commit/aad858dcd106974b3ff1c7ed34c117b2ab89beaa
