### ISSUE TITLE
Info box for emapis layer 

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#25]
We'd need also infobox for the "strukturverbesserungen" layers.

**Comment by AFoletti** [comment]
The basic chsdi info is now in the BOD.
CHSDI will still not be able to use it, since the layers have at the moment no topic. This will be corrected by Mario tomorrow

**Comment by AFoletti** [comment]
Layers are correctly in a topic and should behave exactly as every other chsdi layer
