### ISSUE TITLE
Add tooltip for "Strukturverbesserungen" objects

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#28]
@oterral 
Sorry my mistake in the specifications: forgot to describe this.
We'd need a tooltip also, showing attribute "Geschaeftsnummer".

Thanks

**Comment by oterral** [comment]
@kandre using this https://github.com/geoadmin/ol3/blob/master/src/ol/renderer/maprenderer.js#L187
wiht modifying the curor on mouse over.

**Comment by kandre** [comment]
Ok thanks for the tips

**Comment by oterral** [comment]
Fixed on prod web-emapis.prod.bgdic.ch
