### ISSUE TITLE
WMS doesn't allow big images

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#29]
With screen with high resolution, we can't dipsplay the layer

http://wms-test.dev.bgdi.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.blw.emapis-entwaesserung&CRS=EPSG%3A21781&STYLES=&MAP_RESOLUTION=180&WIDTH=5040&HEIGHT=1218&BBOX=765720%2C154586.5%2C773280%2C156413.5

**Comment by AFoletti** [comment]
Ouch, that's high res :-D
I made it possible up to 8192 pixels, but only on wms-bod

**Comment by oterral** [comment]
We haven't specify the ratio I think, @kandre can you change this pls? http://openlayers.org/en/master/apidoc/ol.source.ImageWMS.html
