### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#3]
Add an input search.

See http://api3.geo.admin.ch/examples/geoadmin_search.html for an example

Search by locations and by coordinates

**Comment by kandre** [comment]
Therefore we dont provide a search by layers? This is not defined in the spec

**Comment by kandre** [comment]
I would say it could come after the first prototype and discussions with IKP

**Comment by oterral** [comment]
no there is a beautiful catalog to search layers
