### ISSUE TITLE
[Search] - IE11

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#32]
@oterral 
Search does not work on IE11

**Comment by oterral** [comment]
Works from outside the bund network (WIFI)  there is a bund configuration settings in IE which block the request.

I'll look for a workarund

**Comment by oterral** [comment]
I've put the development address in http://web-emapis.prod.bgdi.ch/ , so it works but we ned to find a better solution

**Comment by oterral** [comment]
A ticket has been opened for IT, wait and see

**Comment by oterral** [comment]
Fixed on prod
