### ISSUE TITLE
[Permalink] - clarification on "massnahme"

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#33]
@oterral 
The parameter "massnahme" should behave like "layers" in map.geo.admin.ch. Consider it as an alias to "layers". Meaning I can use it to activate the visualisation of layers.

With the URL http://web-emapis.prod.bgdi.ch/ nothing is shown.
With http://web-emapis.prod.bgdi.ch/?masshanme=a,b,c,d,...,z, the layers a,b,c,... are visualised.

**Comment by oterral** [comment]
@kandre only the default behavior must be changed. Display nothing by default.

**Comment by kandre** [comment]
Do we keep the ability to easily set 'default layers' ?
