### ISSUE TITLE
[Filter] - behaviour

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#34]
@oterral 
The filters apply to the layers under "massnahme".
In http://web-emapis.prod.bgdi.ch/?massnahme=ch.blw.emapis-wegebau&typ=5214 the filter applies only to ch.blw.emapis-wegebau. Meaning the user should be able to add other layers from "Strukturverbesserungen", which will not be filtered.

**Comment by kandre** [comment]
Good point

**Comment by kandre** [comment]
It also means that if a layer is in the permalink and filtered (and hence checked at page start), after unselecting and selecting it, we should take care that it is not filtered this time.
