### ISSUE TITLE
[Filter] : Behavior when no massnahme specified but a typ/status/projekt

### ISSUE THREAD

**Issue by kandre** [geoadmin/web-emapis#38]
If there is no massnahme in the permalink but a typ/status/projekt specified, all the layers under 'Strukturverbesserungen' are shown and filter is applied to all of them.

**Comment by p1d1d1** [comment]
@kandre @oterral 
Alternatively we could use a more map.geo.admin.ch-oriented approach.
Meaning that layers (massnahme) should always be specified. A layers is activated and visualised if in the permalink.
Don't really know.
What do you think?

**Comment by oterral** [comment]
I think , it's easier for people who creates permalink to have the possibitlity to display only filter parameters and not all the layers names.

**Comment by p1d1d1** [comment]
Yes for sure.... so if it's not an issue for you, we can leave as it is.
