### ISSUE TITLE
Catalog 

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#4]
An toggle element  which display a tree of predefined WMS layers.

See http://api3.geo.admin.ch/examples/geoadmin_catalog.html for an example

**Comment by p1d1d1** [comment]
We'd need also infobox for the "strukturverbesserungen" layers.
Thanks

**Comment by oterral** [comment]
I create an issue for that. #25

**Comment by p1d1d1** [comment]
CSS problem for Infobox: class-modalgialog
Thanks

**Comment by oterral** [comment]
You can create separate issues  @p1d1d1   https://github.com/geoadmin/web-emapis/issues/26
