### ISSUE TITLE
Database: geschaeftsnummer should be an integer

### ISSUE THREAD

**Issue by kandre** [geoadmin/web-emapis#42]
@AFoletti, in my opinion, geschaeftsnummer in DB should be an integer or at least set a new attribute geschaeftsnummer_code as integer.

**Comment by AFoletti** [comment]
The model says it's a text, but I fully agree with you.
Christine had some discussions with the data owner about their [*censure*] model, and they will hopefully implement codes everywhere (at the moment, the model is fully text-based). But even if we will still get text, I'll add an integer code to simplify

**Comment by kandre** [comment]
Ok, thank for that information
