### ISSUE TITLE
Defaul map.geo.admin.ch Logo

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#50]
@oterral 
Olivier how much effort will be to put top-left the default logo we have in map.geo.admin.ch and delete the text "emapis logo"? - default behaviour on click
I'd prefer to not have an emapis logo, which by the way doesn't exist yet.
We'll see in the future if they really want it.
Thanks

**Comment by oterral** [comment]
I think it can be very quick, what do you think @pfanguin ?

**Comment by pfanguin** [comment]
I do that

**Comment by p1d1d1** [comment]
@oterral 
what does it mean when you close issue like this one?
That the issue is fixed/will be fixed with a next "kind of deploy"?

**Comment by oterral** [comment]
Exactly it is fixed in master so available on next deploy. I'll will add a comment next time. If you prefer I close when it'as available on web-emapis.pro.bgdi.ch ?

**Comment by p1d1d1** [comment]
Yes please, if it's not a problem for you I'd prefer you close when on web-emapis.

**Comment by oterral** [comment]
no problem
