### ISSUE TITLE
[Tooltip]: cursor does not change everywhere on hatched features

### ISSUE THREAD

**Issue by kandre** [geoadmin/web-emapis#55]
When hovering a feature, the mouse cursor will change to show that a tootip is available (#28). 

However, at the moment, the cursor change only when it matches for example a line/point of the feature. Meaning that on a hatched features, the transparent part is not matched, leading to a fuzzy cursor change.

I suggest @AFoletti to add a style (first position) in the mapfile with an opacity almost transparent (to let the map visible behind) but still detectable by the cursor. What do you think?

Example: 

Adding:

      STYLE
         COLOR 255 254 255
         OPACITY 1
      END

To have: 

    CLASS
      NAME "5414"
      EXPRESSION "5414"
      MAXSCALEDENOM 45000
      STYLE
         COLOR 255 254 255
         OPACITY 1
      END
      STYLE
        OUTLINECOLOR 77 230 0
        OUTLINEWIDTH 1
      END
      STYLE
        SYMBOL "hatch"
        SIZE 6
        COLOR 77 230 0
        ANGLE 90
        WIDTH 1
      END
    END

Result: transparent feature, and the cursor captures the feature anywhere

![wms](https://cloud.githubusercontent.com/assets/8038575/6366961/51c86826-bccd-11e4-9c3f-2cf12afe0b47.png)

**Comment by AFoletti** [comment]
May I ask how do you achieve the changeing cursor effect?

**Comment by kandre** [comment]
I use the new ol3 function forEachLayerAtPixel: 

It is based on a matched colored-value pixel on the viewport and return true if it is detected. Hence no problem if several layer are detected on a given pixel: it return true and the cursor is changed to a hand.

http://openlayers.org/en/v3.2.1/apidoc/ol.Map.html?unstable=true#forEachLayerAtPixel

**Comment by AFoletti** [comment]
Let's talk about the technical details tomorrow ;). It's quite clear in practice, but I'd like to better understand the functioning of all this.

Anyways... I'll add the needed STYLE to the classes

**Comment by kandre** [comment]
Yes of course, no emergency at all

**Comment by AFoletti** [comment]
I added the invisible STYLE to each non-filled polygon. Could you please test that?

**Comment by kandre** [comment]
@AFoletti this works very well on chrome, I like the behavior (I had some unrelated problems on FF and IE11, then not tested on them). 

Like you said, we can have some problems with CH-covering polygons. Do you know or think we could have such cased with our layers in eMapis ?

**Comment by AFoletti** [comment]
No, for the emapis layers we will (most probably) not have very big polygons so it's a safe approach

**Comment by oterral** [comment]
@kandre can you use that doing the stuff of tooltips?

**Comment by kandre** [comment]
you mean the forEachLayerAtPixel stuff ?

**Comment by oterral** [comment]
yes

**Comment by kandre** [comment]
yes, really nth !

**Comment by oterral** [comment]
Fixed web-emapis.prod.bgdic.ch
