### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#57]
@oterral 
Please same bahaviour as in map.geo.admin.ch.
Now it is anchored at a point on/in the queried object. This leads to not nice situations where the tooltip is hidden by the catalog or by the header. See pictures
![cattura](https://cloud.githubusercontent.com/assets/1533649/6367309/babf223a-bcd1-11e4-98e0-751fbbca6d09.JPG)
![cattura2](https://cloud.githubusercontent.com/assets/1533649/6367310/bcc64a5e-bcd1-11e4-8a06-34f84059bae6.JPG)

**Comment by oterral** [comment]
All popup stuff will be fixed with #59 so I close this one.
