### ISSUE TITLE
[Print] - a marker is printed

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/web-emapis#68]
Randomly a marker is printed

![image](https://cloud.githubusercontent.com/assets/1533649/6523835/cc41681e-c3f3-11e4-9781-3c43d496eda9.png)

**Comment by kandre** [comment]
This happens when we rigth-clic the map: no marker is displayed but however it is printed

**Comment by kandre** [comment]
errata: it happens also with left-clic (without dragging)

**Comment by loicgasser** [comment]
I may have seen this problem in Geoadmin as well. It is hard to reproduce though.

**Comment by kandre** [comment]
You are right, I think it is something similar as #2163.

In emapis, I can reproduce it everytime.

**Comment by loicgasser** [comment]
I think this is browser specific in geoadmin.

**Comment by oterral** [comment]
It was fixed in geoadmin
