### ISSUE TITLE
Measure

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#7]
Add a link whcih can toggle a measure tool 

See http://openlayers.org/en/v3.2.0/examples/measure.html for an example.

**Comment by kandre** [comment]
I suggest at first we do almost the same as in the example meaning returning distance after one click, and an area after 2 clicks or more, but distance as well

**Comment by oterral** [comment]
an all-in-one measure like in geoadmin should be better yes.

**Comment by kandre** [comment]
therefore with azimut of first line

**Comment by oterral** [comment]
azimuth is not necessary I think.

**Comment by kandre** [comment]
ok

**Comment by oterral** [comment]
ready on prod
