### ISSUE TITLE
Display all emapis layers int the catalog 

### ISSUE THREAD

**Issue by oterral** [geoadmin/web-emapis#91]
@AFoletti waht is the status of emapis layers are they all available in your branch of chsdi?

**Comment by AFoletti** [comment]
yep, each eMapis layer should be available in this branch:
https://github.com/geoadmin/mf-chsdi3/compare/kan_chsdi_emapis_entwaesserung

**Comment by oterral** [comment]
perfect @kandre can you add those int the catalog?
